In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(0.4, 10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
#float object cannot be interpreted as an inter

In [7]:
#In the code below, the first value is for start, second one for stop and the last value is for step.
#One thing that should be noted down: the stop value is not inclusive, means it is excluded.
list(np.arange(.4, 10.4, 0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [9]:
#This linspace function generates the number within the given interval with equal gap
np.linspace(1,5, 20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [10]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [13]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [14]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [19]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
arr = np.ones((3,4))

In [22]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
arr + 5   # every element is added by 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [24]:
arr * 4    #every element is multiplied by 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [27]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [32]:
#this creates an identity matrix
arr1 = np.eye(5)

In [33]:
arr1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
import pandas as pd

In [35]:
pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [36]:
np.random.rand(2,3)

array([[0.96211494, 0.80036197, 0.75830031],
       [0.95367478, 0.95023163, 0.90072173]])

In [39]:
#generates the random numbers from standard normal distribution with mean=0 and variance=1
np.random.randn(2,3)

array([[ 0.53328084,  1.93055561, -0.21978744],
       [-0.75361176,  0.19195281,  0.24694182]])

In [42]:
#This will generate random integers between 1 and 4 (inclusive)
arr2 = np.random.randint(1,5, (3,4))

In [43]:
arr2

array([[3, 1, 1, 1],
       [1, 2, 2, 1],
       [1, 1, 1, 1]])

In [44]:
arr2.size #counting the total numbers in the array

12

In [45]:
arr1.ndim

2

In [47]:
arr2.ndim   # ndim returns the dimensions of the array

2

In [50]:
arr3 = arr2.reshape(6,2)

In [51]:
arr2.shape

(3, 4)

In [52]:
arr3

array([[3, 1],
       [1, 1],
       [1, 2],
       [2, 1],
       [1, 1],
       [1, 1]])

In [54]:
arr3.shape  # the shape of the array has been changed

(6, 2)

In [56]:
arr4 = arr2.reshape(2,6)

In [57]:
arr4

array([[3, 1, 1, 1, 1, 2],
       [2, 1, 1, 1, 1, 1]])

In [58]:
arr2

array([[3, 1, 1, 1],
       [1, 2, 2, 1],
       [1, 1, 1, 1]])

In [59]:
#shape of arr4 and arr2 can be seen different from each other

In [60]:
arr2.reshape(4,-1)

array([[3, 1, 1],
       [1, 1, 2],
       [2, 1, 1],
       [1, 1, 1]])

In [61]:
arr2.reshape(4, -143289)

array([[3, 1, 1],
       [1, 1, 2],
       [2, 1, 1],
       [1, 1, 1]])

In [62]:
#he -1 in the second argument of the reshape() function is a placeholder for an 
#unknown dimension. In this case, NumPy will automatically calculate the correct 
#value for that dimension based on the size of the original array and the other 
#specified dimension