In [1]:
#put the index 

import pandas as pd
variable = pd.Series([8,3,6,5,1], index = ['b', 'd','c', 'e','f'])

In [2]:
variable

b    8
d    3
c    6
e    5
f    1
dtype: int64

In [3]:
my_list = ['apple', 'banana' , 'cherry','mango','pineapple']

In [6]:
variable.reindex(my_list)

apple       NaN
banana      NaN
cherry      NaN
mango       NaN
pineapple   NaN
dtype: float64

In [7]:
variable

b    8
d    3
c    6
e    5
f    1
dtype: int64

In [10]:
#sort the index of the series
new_variable = variable.sort_index()

In [11]:
new_variable

b    8
c    6
d    3
e    5
f    1
dtype: int64

In [13]:
#sort the values
sort_value =new_variable.sort_values()

In [14]:
sort_value

f    1
d    3
e    5
c    6
b    8
dtype: int64

In [15]:
# Both the index and values of the series can be sorted

In [16]:
variable

b    8
d    3
c    6
e    5
f    1
dtype: int64

In [17]:
variable.isin([6,1])

b    False
d    False
c     True
e    False
f     True
dtype: bool

In [18]:
variable[variable.isin([6,1])]

c    6
f    1
dtype: int64

In [19]:
type(variable)

pandas.core.series.Series

In [20]:
type(variable[variable.isin([6,1])])

pandas.core.series.Series

In [21]:
variable.ndim

1

In [22]:
#series has only one dimension 

In [23]:
variable.values

array([8, 3, 6, 5, 1], dtype=int64)

In [25]:
#list comprehension to iterate values
[i for i in variable.values]

[8, 3, 6, 5, 1]

In [26]:
#list comprehension to iterate on index
variable.index

Index(['b', 'd', 'c', 'e', 'f'], dtype='object')

In [29]:
[i for i in variable.index]

['b', 'd', 'c', 'e', 'f']

In [30]:
variable.items

<bound method Series.items of b    8
d    3
c    6
e    5
f    1
dtype: int64>

In [31]:
variable.items()

In [32]:
list(variable.items())

[('b', 8), ('d', 3), ('c', 6), ('e', 5), ('f', 1)]

In [33]:
for index, value in variable.items():
    print(index,value)

b 8
d 3
c 6
e 5
f 1


for index, value in variable.items():
    print(value,index)

In [36]:
for index, value in variable.items():
    print(index, "-", value)

b - 8
d - 3
c - 6
e - 5
f - 1


# Indexing and Slicing in Pandas

In [37]:
import pandas as pd

In [38]:
example = pd.Series(['+67', '+90', '+44','+50','+59', '+34','+96'], index = ['Germany', 'Nepal', "India", 'Japan', 'Pakistan', 'America', 'Bhutan'])

In [39]:
example

Germany     +67
Nepal       +90
India       +44
Japan       +50
Pakistan    +59
America     +34
Bhutan      +96
dtype: object

In [40]:
example['Bhutan']

'+96'

In [41]:
# NOTE: We can use numerical index also
example[1]

'+90'

In [43]:
#slicing
#NOTE: both the start and end values are inclusive
example["Nepal" : "America"]

Nepal       +90
India       +44
Japan       +50
Pakistan    +59
America     +34
dtype: object

In [44]:
#Slicing using the numerical index
example[2:5]

India       +44
Japan       +50
Pakistan    +59
dtype: object

# [Start: Stop: Step]

In [45]:
example[2:5:2]

India       +44
Pakistan    +59
dtype: object

In [46]:
example['India']

'+44'

In [47]:
# to get the values of 2 or more, pass their index as a list
example['India', 'Nepal']

KeyError: 'key of type tuple not found and not a MultiIndex'

In [48]:
#pass the list to get the values of 2 or more 
example[['India', 'Pakistan']]

India       +44
Pakistan    +59
dtype: object

# Adding Columns to Data frames

In [49]:
import numpy as np
import pandas as pd

In [50]:
x = np.arange(0,28)

In [51]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [52]:
y = np.arange(10)

In [53]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
z = np.arange(1,21)

In [55]:
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [56]:
#The the boundary is exclusive

In [57]:
x.reshape(7,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

# Changing the data to DataFrame

In [59]:
x =x.reshape(7,4)
df = pd.DataFrame(data = x, columns = ['col1', 'col2', 'col3', 'col4'])

In [61]:
df

col1  col2  col3  col4
0     0     1     2     3
1     4     5     6     7
2     8     9    10    11
3    12    13    14    15
4    16    17    18    19
5    20    21    22    23
6    24    25    26    27

# Use of dropna()

In [70]:
new_df = df.drop(['col4'],axis = 1)

In [72]:
# the col4 column has been dropped, asis should always be mentioned
new_df

col1  col2  col3
0     0     1     2
1     4     5     6
2     8     9    10
3    12    13    14
4    16    17    18
5    20    21    22
6    24    25    26

In [74]:
df['col5'] = df['col1'] + df['col2']

In [75]:
df

col1  col2  col3  col4  col5
0     0     1     2     3     1
1     4     5     6     7     9
2     8     9    10    11    17
3    12    13    14    15    25
4    16    17    18    19    33
5    20    21    22    23    41
6    24    25    26    27    49

In [76]:
df['col6'] = df['col4'] * df['col3']

In [77]:
df

col1  col2  col3  col4  col5  col6
0     0     1     2     3     1     6
1     4     5     6     7     9    42
2     8     9    10    11    17   110
3    12    13    14    15    25   210
4    16    17    18    19    33   342
5    20    21    22    23    41   506
6    24    25    26    27    49   702

In [78]:
np.arange(28,35)

array([28, 29, 30, 31, 32, 33, 34])

In [82]:
df['col7'] = np.arange(28,35)

In [80]:
df

col1  col2  col3  col4  col5  col6  col7
0     0     1     2     3     1     6    28
1     4     5     6     7     9    42    29
2     8     9    10    11    17   110    30
3    12    13    14    15    25   210    31
4    16    17    18    19    33   342    32
5    20    21    22    23    41   506    33
6    24    25    26    27    49   702    34

In [83]:
#NOTE: if size of the new col doesn't match then an error will raise

# Setting the index in pandas DataFrame

In [84]:
import numpy as np
import pandas as pd

In [91]:
np.random.seed(101)
df = pd.DataFrame(data = np.random.randn(6,5), index = "A B C D E F".split(), columns = "val1 val2 val3 val4 val5".split())

In [92]:
df

val1      val2      val3      val4      val5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

In [93]:
df

val1      val2      val3      val4      val5
A  2.706850  0.628133  0.907969  0.503826  0.651118
B -0.319318 -0.848077  0.605965 -2.018168  0.740122
C  0.528813 -0.589001  0.188695 -0.758872 -0.933237
D  0.955057  0.190794  1.978757  2.605967  0.683509
E  0.302665  1.693723 -1.706086 -1.159119 -0.134841
F  0.390528  0.166905  0.184502  0.807706  0.072960

# Another example of dataframe

In [94]:
import numpy as np
import pandas as pd

In [96]:
np.random.seed(10)

In [97]:
my_data = np.random.randn(6,6)

In [99]:
index = "1,2,3,4,5,6".split(',')

In [100]:
columns = "first,second,third,fourth,fifth,sixth".split(',')

In [101]:
df = pd.DataFrame(data=my_data, index=index, columns=columns)

In [102]:
df

first    second     third    fourth     fifth     sixth
1  1.331587  0.715279 -1.545400 -0.008384  0.621336 -0.720086
2  0.265512  0.108549  0.004291 -0.174600  0.433026  1.203037
3 -0.965066  1.028274  0.228630  0.445138 -1.136602  0.135137
4  1.484537 -1.079805 -1.977728 -1.743372  0.266070  2.384967
5  1.123691  1.672622  0.099149  1.397996 -0.271248  0.613204
6 -0.267317 -0.549309  0.132708 -0.476142  1.308473  0.195013

# One more example 

In [103]:
import numpy as np
import pandas as pd
np.random.seed(99)

In [104]:
new_data = np.random.randn(9,9)

In [106]:
index_used = "1#2#3#4#5#6#7#8#9".split('#')
columns_used = "col1#col2#col3#col4#col5#col6#col7#col8#col9".split('#')

In [107]:
df = pd.DataFrame(data=new_data, index=index_used,columns=columns_used)

In [108]:
df

col1      col2      col3      col4      col5      col6      col7  \
1 -0.142359  2.057222  0.283262  1.329812 -0.154622 -0.069031  0.755180   
2 -2.367838 -0.167049  0.685398  0.023500  0.456201  0.270493 -1.435008   
3 -0.501565  0.590953 -0.731616  0.261755 -0.855796 -0.187526 -0.373486   
4 -0.045123  0.121328  0.925953 -0.573820  0.052703  2.207311  0.391822   
5 -1.704292 -0.243908 -2.139704  0.861323  1.700284 -0.528785  1.763478   
6  0.552732 -0.815981 -0.496647  1.086226 -0.974675 -0.282136 -0.117214   
7 -0.103571 -1.198706  1.010036  2.875360  0.820313  0.560612 -0.375642   
8  0.617332 -0.135787  1.287905 -1.036994  1.364332 -0.309957 -0.611117   
9 -2.088335  0.639322  0.774304  1.278569  0.705276  0.655977 -1.678502   

       col8      col9  
1  0.825647 -0.113069  
2  0.882817 -0.580082  
3 -0.461971 -0.816466  
4  0.482713  0.433334  
5 -1.121608 -1.191934  
6  0.378547  0.732195  
7 -0.252104 -1.389613  
8 -0.483106 -0.608984  
9  0.183110 -1.133224

In [110]:
#This transforms the index of the df starting from 0 and goes up
df.reset_index()

index      col1      col2      col3      col4      col5      col6      col7  \
0     1 -0.142359  2.057222  0.283262  1.329812 -0.154622 -0.069031  0.755180   
1     2 -2.367838 -0.167049  0.685398  0.023500  0.456201  0.270493 -1.435008   
2     3 -0.501565  0.590953 -0.731616  0.261755 -0.855796 -0.187526 -0.373486   
3     4 -0.045123  0.121328  0.925953 -0.573820  0.052703  2.207311  0.391822   
4     5 -1.704292 -0.243908 -2.139704  0.861323  1.700284 -0.528785  1.763478   
5     6  0.552732 -0.815981 -0.496647  1.086226 -0.974675 -0.282136 -0.117214   
6     7 -0.103571 -1.198706  1.010036  2.875360  0.820313  0.560612 -0.375642   
7     8  0.617332 -0.135787  1.287905 -1.036994  1.364332 -0.309957 -0.611117   
8     9 -2.088335  0.639322  0.774304  1.278569  0.705276  0.655977 -1.678502   

       col8      col9  
0  0.825647 -0.113069  
1  0.882817 -0.580082  
2 -0.461971 -0.816466  
3  0.482713  0.433334  
4 -1.121608 -1.191934  
5  0.378547  0.732195  
6 -0.252104 -1.389613  
7 -0.483106 -0.608984  
8  0.183110 -1.133224

In [111]:
df

col1      col2      col3      col4      col5      col6      col7  \
1 -0.142359  2.057222  0.283262  1.329812 -0.154622 -0.069031  0.755180   
2 -2.367838 -0.167049  0.685398  0.023500  0.456201  0.270493 -1.435008   
3 -0.501565  0.590953 -0.731616  0.261755 -0.855796 -0.187526 -0.373486   
4 -0.045123  0.121328  0.925953 -0.573820  0.052703  2.207311  0.391822   
5 -1.704292 -0.243908 -2.139704  0.861323  1.700284 -0.528785  1.763478   
6  0.552732 -0.815981 -0.496647  1.086226 -0.974675 -0.282136 -0.117214   
7 -0.103571 -1.198706  1.010036  2.875360  0.820313  0.560612 -0.375642   
8  0.617332 -0.135787  1.287905 -1.036994  1.364332 -0.309957 -0.611117   
9 -2.088335  0.639322  0.774304  1.278569  0.705276  0.655977 -1.678502   

       col8      col9  
1  0.825647 -0.113069  
2  0.882817 -0.580082  
3 -0.461971 -0.816466  
4  0.482713  0.433334  
5 -1.121608 -1.191934  
6  0.378547  0.732195  
7 -0.252104 -1.389613  
8 -0.483106 -0.608984  
9  0.183110 -1.133224

In [112]:
df.reset_index(drop=True)

col1      col2      col3      col4      col5      col6      col7  \
0 -0.142359  2.057222  0.283262  1.329812 -0.154622 -0.069031  0.755180   
1 -2.367838 -0.167049  0.685398  0.023500  0.456201  0.270493 -1.435008   
2 -0.501565  0.590953 -0.731616  0.261755 -0.855796 -0.187526 -0.373486   
3 -0.045123  0.121328  0.925953 -0.573820  0.052703  2.207311  0.391822   
4 -1.704292 -0.243908 -2.139704  0.861323  1.700284 -0.528785  1.763478   
5  0.552732 -0.815981 -0.496647  1.086226 -0.974675 -0.282136 -0.117214   
6 -0.103571 -1.198706  1.010036  2.875360  0.820313  0.560612 -0.375642   
7  0.617332 -0.135787  1.287905 -1.036994  1.364332 -0.309957 -0.611117   
8 -2.088335  0.639322  0.774304  1.278569  0.705276  0.655977 -1.678502   

       col8      col9  
0  0.825647 -0.113069  
1  0.882817 -0.580082  
2 -0.461971 -0.816466  
3  0.482713  0.433334  
4 -1.121608 -1.191934  
5  0.378547  0.732195  
6 -0.252104 -1.389613  
7 -0.483106 -0.608984  
8  0.183110 -1.133224

In [113]:
df

col1      col2      col3      col4      col5      col6      col7  \
1 -0.142359  2.057222  0.283262  1.329812 -0.154622 -0.069031  0.755180   
2 -2.367838 -0.167049  0.685398  0.023500  0.456201  0.270493 -1.435008   
3 -0.501565  0.590953 -0.731616  0.261755 -0.855796 -0.187526 -0.373486   
4 -0.045123  0.121328  0.925953 -0.573820  0.052703  2.207311  0.391822   
5 -1.704292 -0.243908 -2.139704  0.861323  1.700284 -0.528785  1.763478   
6  0.552732 -0.815981 -0.496647  1.086226 -0.974675 -0.282136 -0.117214   
7 -0.103571 -1.198706  1.010036  2.875360  0.820313  0.560612 -0.375642   
8  0.617332 -0.135787  1.287905 -1.036994  1.364332 -0.309957 -0.611117   
9 -2.088335  0.639322  0.774304  1.278569  0.705276  0.655977 -1.678502   

       col8      col9  
1  0.825647 -0.113069  
2  0.882817 -0.580082  
3 -0.461971 -0.816466  
4  0.482713  0.433334  
5 -1.121608 -1.191934  
6  0.378547  0.732195  
7 -0.252104 -1.389613  
8 -0.483106 -0.608984  
9  0.183110 -1.133224

In [116]:
#inplace = True, basically changes the df permanently
df.reset_index(inplace=True)

In [117]:
df

level_0 index      col1      col2      col3      col4      col5      col6  \
0        0     1 -0.142359  2.057222  0.283262  1.329812 -0.154622 -0.069031   
1        1     2 -2.367838 -0.167049  0.685398  0.023500  0.456201  0.270493   
2        2     3 -0.501565  0.590953 -0.731616  0.261755 -0.855796 -0.187526   
3        3     4 -0.045123  0.121328  0.925953 -0.573820  0.052703  2.207311   
4        4     5 -1.704292 -0.243908 -2.139704  0.861323  1.700284 -0.528785   
5        5     6  0.552732 -0.815981 -0.496647  1.086226 -0.974675 -0.282136   
6        6     7 -0.103571 -1.198706  1.010036  2.875360  0.820313  0.560612   
7        7     8  0.617332 -0.135787  1.287905 -1.036994  1.364332 -0.309957   
8        8     9 -2.088335  0.639322  0.774304  1.278569  0.705276  0.655977   

       col7      col8      col9  
0  0.755180  0.825647 -0.113069  
1 -1.435008  0.882817 -0.580082  
2 -0.373486 -0.461971 -0.816466  
3  0.391822  0.482713  0.433334  
4  1.763478 -1.121608 -1.191934  
5 -0.117214  0.378547  0.732195  
6 -0.375642 -0.252104 -1.389613  
7 -0.611117 -0.483106 -0.608984  
8 -1.678502  0.183110 -1.133224